### ISSUE TITLE
Projekt ei kompileeru

### ISSUE THREAD

**Issue by Zukkari** [TanelOrumaa/trivia#30]
Klassis `BaseClientBackEnd` 

`import configuration.Config;`

Kompileerimisel tekib viga:

`Error:(5, 21) java: package configuration does not exist`

Vaatasime projekti struktuuri üle ja sellist package-it tegelikult ei olegi olemas.
Vaatasime, see oli lisatud 29 Märts aga nüüd on see kusagile kadunud.

Tundub, et lokaalselt see on teil olemas, kuna arendus ikkagi toimub.
Märkasin, et need failid on lisatud `.gitignore` faili.

Palun lisage vajalikud failid reposse, et saaksime teie tööd hinnata.

**Comment by Juhantam** [comment]
Tere! Kunagi mingi merge conflicti käigus eemaldasime gitignore failist vist lihtsalt kogemata vale rea või panime just kogemata liiga palju sinna. Igaljuhul nüüd peaks olema korrektne examplefile siin repos. Vajalikud andmed obfuscated väljade asendamiseks panen trellosse ja saadan teile meilile.

**Comment by TanelOrumaa** [comment]
Lisan, et fail ja package nimi on ka ülesseadmisõpetuses, mis ma teile meilile saatsin: https://trello.com/c/vkpFZdJm/36-guide-to-use-the-application
